module.exports = {
    LOGIN: 'lOGIN',
    LOGOUT: 'LOGOUT',
    LOADING_UI: 'LOADING_UI',
    UNLOADING_UI: 'UNLOADING_UI',
    SET_ERRORS: 'SET_ERRORS',
    UNSET_ERRORS: 'UNSET_ERRORS',
    ADD_TESTS: 'ADD_TESTS',
    ADD_QUESTIONS: 'ADD_QUESTIONS',
    ADD_ANSWERS: 'ADD_ANSWERS',
    ADD_RESPONSE: 'ADD-RESPONSE',
    CURRENT_TEST: 'CURRENT_TEST',
    CURRENT_ANSWERS: 'CURRENT_ANSWERS',
    QUESTION_STATE: 'QUESTION_STATE',
    TEST_STATE: 'TEST_STATE',
    SET_USER: 'SET_USER',
    GET_DIFFICULTY: 'GET_DIFFICULTY',
    SET_TEST_COMPLETED: 'SET_TEST_COMPLETED'
 };